/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.ultimateMrz.Sdk {

using System;
using System.Runtime.InteropServices;

public class ultimateMrzSdk {
  public static readonly int ULTMRZ_SDK_VERSION_MAJOR = ultimateMrzSdkPINVOKE.ULTMRZ_SDK_VERSION_MAJOR_get();
  public static readonly int ULTMRZ_SDK_VERSION_MINOR = ultimateMrzSdkPINVOKE.ULTMRZ_SDK_VERSION_MINOR_get();
  public static readonly int ULTMRZ_SDK_VERSION_MICRO = ultimateMrzSdkPINVOKE.ULTMRZ_SDK_VERSION_MICRO_get();
}

}
