/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.ultimateMrz.Sdk {

public enum ULTMRZ_SDK_IMAGE_TYPE {
  ULTMRZ_SDK_IMAGE_TYPE_RGB24,
  ULTMRZ_SDK_IMAGE_TYPE_RGBA32,
  ULTMRZ_SDK_IMAGE_TYPE_BGRA32,
  ULTMRZ_SDK_IMAGE_TYPE_NV12,
  ULTMRZ_SDK_IMAGE_TYPE_NV21,
  ULTMRZ_SDK_IMAGE_TYPE_YUV420P,
  ULTMRZ_SDK_IMAGE_TYPE_YVU420P,
  ULTMRZ_SDK_IMAGE_TYPE_YUV422P,
  ULTMRZ_SDK_IMAGE_TYPE_YUV444P,
  ULTMRZ_SDK_IMAGE_TYPE_Y,
  ULTMRZ_SDK_IMAGE_TYPE_BGR24
}

}
