/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.ultimateMrz.Sdk {

using System;
using System.Runtime.InteropServices;

public class UltMrzSdkResult : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UltMrzSdkResult(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(UltMrzSdkResult obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~UltMrzSdkResult() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ultimateMrzSdkPINVOKE.delete_UltMrzSdkResult(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public UltMrzSdkResult() : this(ultimateMrzSdkPINVOKE.new_UltMrzSdkResult__SWIG_0(), true) {
  }

  public UltMrzSdkResult(int code, string phrase, string json, uint numZones) : this(ultimateMrzSdkPINVOKE.new_UltMrzSdkResult__SWIG_1(code, phrase, json, numZones), true) {
  }

  public UltMrzSdkResult(int code, string phrase, string json) : this(ultimateMrzSdkPINVOKE.new_UltMrzSdkResult__SWIG_2(code, phrase, json), true) {
  }

  public UltMrzSdkResult(UltMrzSdkResult other) : this(ultimateMrzSdkPINVOKE.new_UltMrzSdkResult__SWIG_3(UltMrzSdkResult.getCPtr(other)), true) {
    if (ultimateMrzSdkPINVOKE.SWIGPendingException.Pending) throw ultimateMrzSdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public int code() {
    int ret = ultimateMrzSdkPINVOKE.UltMrzSdkResult_code(swigCPtr);
    return ret;
  }

  public string phrase() {
    string ret = ultimateMrzSdkPINVOKE.UltMrzSdkResult_phrase(swigCPtr);
    return ret;
  }

  public string json() {
    string ret = ultimateMrzSdkPINVOKE.UltMrzSdkResult_json(swigCPtr);
    return ret;
  }

  public uint numZones() {
    uint ret = ultimateMrzSdkPINVOKE.UltMrzSdkResult_numZones(swigCPtr);
    return ret;
  }

  public bool isOK() {
    bool ret = ultimateMrzSdkPINVOKE.UltMrzSdkResult_isOK(swigCPtr);
    return ret;
  }

}

}
