/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.ultimateMrz.Sdk;

public class ultimateMrzSdkJNI {

  static {
    System.loadLibrary("ultimateMRZ_SDK");
  }

  public final static native long new_UltMrzSdkResult__SWIG_0(int jarg1, String jarg2, String jarg3, long jarg4);
  public final static native long new_UltMrzSdkResult__SWIG_1(int jarg1, String jarg2, String jarg3);
  public final static native void delete_UltMrzSdkResult(long jarg1);
  public final static native int UltMrzSdkResult_code(long jarg1, UltMrzSdkResult jarg1_);
  public final static native String UltMrzSdkResult_phrase(long jarg1, UltMrzSdkResult jarg1_);
  public final static native String UltMrzSdkResult_json(long jarg1, UltMrzSdkResult jarg1_);
  public final static native long UltMrzSdkResult_numZones(long jarg1, UltMrzSdkResult jarg1_);
  public final static native boolean UltMrzSdkResult_isOK(long jarg1, UltMrzSdkResult jarg1_);
  public final static native long UltMrzSdkEngine_init__SWIG_0(Object jarg1, String jarg2);
  public final static native long UltMrzSdkEngine_init__SWIG_1(Object jarg1);
  public final static native long UltMrzSdkEngine_deInit();
  public final static native long UltMrzSdkEngine_process__SWIG_0(int jarg1, java.nio.ByteBuffer jarg2, long jarg3, long jarg4, long jarg5, int jarg6);
  public final static native long UltMrzSdkEngine_process__SWIG_1(int jarg1, java.nio.ByteBuffer jarg2, long jarg3, long jarg4, long jarg5);
  public final static native long UltMrzSdkEngine_process__SWIG_2(int jarg1, java.nio.ByteBuffer jarg2, long jarg3, long jarg4);
  public final static native long UltMrzSdkEngine_process__SWIG_3(int jarg1, java.nio.ByteBuffer jarg2, java.nio.ByteBuffer jarg3, java.nio.ByteBuffer jarg4, long jarg5, long jarg6, long jarg7, long jarg8, long jarg9, long jarg10, int jarg11);
  public final static native long UltMrzSdkEngine_process__SWIG_4(int jarg1, java.nio.ByteBuffer jarg2, java.nio.ByteBuffer jarg3, java.nio.ByteBuffer jarg4, long jarg5, long jarg6, long jarg7, long jarg8, long jarg9, long jarg10);
  public final static native long UltMrzSdkEngine_process__SWIG_5(int jarg1, java.nio.ByteBuffer jarg2, java.nio.ByteBuffer jarg3, java.nio.ByteBuffer jarg4, long jarg5, long jarg6, long jarg7, long jarg8, long jarg9);
  public final static native long UltMrzSdkEngine_requestRuntimeLicenseKey__SWIG_0(boolean jarg1);
  public final static native long UltMrzSdkEngine_requestRuntimeLicenseKey__SWIG_1();
  public final static native void delete_UltMrzSdkEngine(long jarg1);
}
