/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.ultimateMrz.Sdk;

public class UltMrzSdkResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UltMrzSdkResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UltMrzSdkResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ultimateMrzSdkJNI.delete_UltMrzSdkResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UltMrzSdkResult() {
    this(ultimateMrzSdkJNI.new_UltMrzSdkResult__SWIG_0(), true);
  }

  public UltMrzSdkResult(int code, String phrase, String json, long numZones) {
    this(ultimateMrzSdkJNI.new_UltMrzSdkResult__SWIG_1(code, phrase, json, numZones), true);
  }

  public UltMrzSdkResult(int code, String phrase, String json) {
    this(ultimateMrzSdkJNI.new_UltMrzSdkResult__SWIG_2(code, phrase, json), true);
  }

  public UltMrzSdkResult(UltMrzSdkResult other) {
    this(ultimateMrzSdkJNI.new_UltMrzSdkResult__SWIG_3(UltMrzSdkResult.getCPtr(other), other), true);
  }

  public int code() {
    return ultimateMrzSdkJNI.UltMrzSdkResult_code(swigCPtr, this);
  }

  public String phrase() {
    return ultimateMrzSdkJNI.UltMrzSdkResult_phrase(swigCPtr, this);
  }

  public String json() {
    return ultimateMrzSdkJNI.UltMrzSdkResult_json(swigCPtr, this);
  }

  public long numZones() {
    return ultimateMrzSdkJNI.UltMrzSdkResult_numZones(swigCPtr, this);
  }

  public boolean isOK() {
    return ultimateMrzSdkJNI.UltMrzSdkResult_isOK(swigCPtr, this);
  }

}
